import datetime


QUOTES = [
    {"text": "Do the best you can until you know better. Then when you know better, do better.", "author": "Maya Angelou"},
    {"text": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Will Durant"},
    {"text": "Success is the product of daily habits, not once-in-a-lifetime transformations.", "author": "James Clear"},
    {"text": "What gets measured gets managed.", "author": "Peter Drucker"},
    {"text": "Discipline is choosing between what you want now and what you want most.", "author": "Abraham Lincoln"},
    {"text": "Small deeds done are better than great deeds planned.", "author": "Peter Marshall"},
    {"text": "Action expresses priorities.", "author": "Mahatma Gandhi"},
    {"text": "A year from now you may wish you had started today.", "author": "Karen Lamb"},
    {"text": "It always seems impossible until it's done.", "author": "Nelson Mandela"},
    {"text": "You do not rise to the level of your goals. You fall to the level of your systems.", "author": "James Clear"},
    {"text": "Well begun is half done.", "author": "Aristotle"},
    {"text": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"text": "The future depends on what you do today.", "author": "Mahatma Gandhi"},
    {"text": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats"},
    {"text": "Great things are done by a series of small things brought together.", "author": "Vincent van Gogh"},
    {"text": "The man who moves a mountain begins by carrying away small stones.", "author": "Confucius"},
    {"text": "Energy and persistence conquer all things.", "author": "Benjamin Franklin"},
    {"text": "Motivation gets you going, but discipline keeps you growing.", "author": "John C. Maxwell"},
    {"text": "If you want to change your life, change your days.", "author": "Unknown"},
    {"text": "Done is better than perfect.", "author": "Sheryl Sandberg"},
    {"text": "The best way out is always through.", "author": "Robert Frost"},
    {"text": "An inch of movement will bring you closer to your goals than a mile of intention.", "author": "Steve Maraboli"},
    {"text": "Nothing will work unless you do.", "author": "Maya Angelou"},
    {"text": "You miss 100 percent of the shots you never take.", "author": "Wayne Gretzky"},
    {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"text": "Fortune favors the bold.", "author": "Virgil"},
    {"text": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu"},
    {"text": "A little progress each day adds up to big results.", "author": "Satya Nani"},
    {"text": "The harder you work for something, the greater you'll feel when you achieve it.", "author": "Unknown"},
    {"text": "Dreams do not work unless you do.", "author": "John C. Maxwell"},
    {"text": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"text": "If it matters to you, you'll find a way.", "author": "Charlie Gilkey"},
    {"text": "You don't have to be extreme, just consistent.", "author": "Unknown"},
    {"text": "Focus on being productive instead of busy.", "author": "Tim Ferriss"},
    {"text": "Starve your distractions, feed your focus.", "author": "Unknown"},
    {"text": "Suffer the pain of discipline or suffer the pain of regret.", "author": "Jim Rohn"},
    {"text": "The difference between ordinary and extraordinary is that little extra.", "author": "Jimmy Johnson"},
    {"text": "A good plan violently executed now is better than a perfect plan executed next week.", "author": "George S. Patton"},
    {"text": "Do something today that your future self will thank you for.", "author": "Sean Patrick Flanery"},
    {"text": "Successful people are simply those with successful habits.", "author": "Brian Tracy"},
    {"text": "You cannot improve what you do not measure.", "author": "Tom DeMarco"},
    {"text": "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "author": "Stephen King"},
    {"text": "The pain of parting is nothing to the joy of meeting again.", "author": "Charles Dickens"},
    {"text": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee"},
    {"text": "You will never always be motivated, so you must learn to be disciplined.", "author": "Unknown"},
    {"text": "Consistency is what transforms average into excellence.", "author": "Robin Sharma"},
    {"text": "The magic you're looking for is in the work you're avoiding.", "author": "Dipen Parmar"},
    {"text": "First forget inspiration. Habit is more dependable.", "author": "Octavia Butler"},
    {"text": "If you get tired, learn to rest, not to quit.", "author": "Banksy"},
    {"text": "Great acts are made up of small deeds.", "author": "Lao Tzu"},
    {"text": "Make each day your masterpiece.", "author": "John Wooden"},
    {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
    {"text": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"text": "You become what you give your attention to.", "author": "Epictetus"},
    {"text": "What you do every day matters more than what you do once in a while.", "author": "Gretchen Rubin"},
    {"text": "There is no substitute for hard work.", "author": "Thomas Edison"},
    {"text": "Your habits will determine your future.", "author": "Jack Canfield"},
    {"text": "When nothing is certain, anything is possible.", "author": "Mandy Hale"},
    {"text": "The obstacle is the way.", "author": "Marcus Aurelius"},
    {"text": "It is never too late to be what you might have been.", "author": "George Eliot"},
    {"text": "If you want something you've never had, you must be willing to do something you've never done.", "author": "Thomas Jefferson"},
    {"text": "Do first things first, and second things not at all.", "author": "Peter Drucker"},
    {"text": "The key is not to prioritize what's on your schedule, but to schedule your priorities.", "author": "Stephen Covey"},
    {"text": "A champion is someone who gets up when they can't.", "author": "Jack Dempsey"},
    {"text": "Perseverance is not a long race; it is many short races one after the other.", "author": "Walter Elliot"},
    {"text": "You may delay, but time will not.", "author": "Benjamin Franklin"},
    {"text": "Time is what we want most, but what we use worst.", "author": "William Penn"},
    {"text": "Where focus goes, energy flows.", "author": "Tony Robbins"},
    {"text": "Small disciplines repeated with consistency every day lead to great achievements.", "author": "John C. Maxwell"},
    {"text": "The beginning is the most important part of the work.", "author": "Plato"},
    {"text": "A river cuts through rock not because of its power, but because of its persistence.", "author": "James N. Watkins"},
    {"text": "Do not let what you cannot do interfere with what you can do.", "author": "John Wooden"},
    {"text": "You are what you do, not what you say you'll do.", "author": "Carl Jung"},
    {"text": "Some people want it to happen, some wish it would happen, others make it happen.", "author": "Michael Jordan"},
    {"text": "Without hustle, talent will only carry you so far.", "author": "Gary Vaynerchuk"},
    {"text": "The cost of procrastination is the life you could have lived.", "author": "Unknown"},
    {"text": "Simple scales. Fancy fails.", "author": "Unknown"},
    {"text": "One day or day one. You decide.", "author": "Paulo Coelho"},
    {"text": "The standard you walk past is the standard you accept.", "author": "David Morrison"},
    {"text": "Clarity comes from engagement, not thought.", "author": "Marie Forleo"},
    {"text": "Inspiration exists, but it has to find you working.", "author": "Pablo Picasso"},
    {"text": "The only impossible journey is the one you never begin.", "author": "Tony Robbins"},
    {"text": "Keep going. Everything you need will come to you at the perfect time.", "author": "Unknown"},
    {"text": "Success doesn't come from what you do occasionally, it comes from what you do consistently.", "author": "Marie Forleo"},
    {"text": "Never confuse movement with action.", "author": "Ernest Hemingway"},
    {"text": "The habit of writing for my eye is good practice. It loosens the ligaments.", "author": "Virginia Woolf"},
    {"text": "You can't build a reputation on what you are going to do.", "author": "Henry Ford"},
    {"text": "We become what we think about.", "author": "Earl Nightingale"},
    {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
    {"text": "Light tomorrow with today.", "author": "Elizabeth Barrett Browning"},
    {"text": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt"},
    {"text": "Everything you've ever wanted is on the other side of consistency.", "author": "Unknown"},
    {"text": "Routine, in an intelligent person, is a sign of ambition.", "author": "W. H. Auden"},
    {"text": "The main thing is to keep the main thing the main thing.", "author": "Stephen Covey"},
    {"text": "How we spend our days is, of course, how we spend our lives.", "author": "Annie Dillard"},
    {"text": "Keep your eyes on the stars, and your feet on the ground.", "author": "Theodore Roosevelt"},
    {"text": "The quieter you become, the more you can hear.", "author": "Ram Dass"},
    {"text": "A goal without a plan is just a wish.", "author": "Antoine de Saint-Exupery"},
    {"text": "Practice puts brains in your muscles.", "author": "Sam Snead"},
    {"text": "Don't count the days, make the days count.", "author": "Muhammad Ali"},
    {"text": "Work while they sleep. Learn while they party. Save while they spend.", "author": "Unknown"},
    {"text": "Progress, not perfection.", "author": "Unknown"},
    {"text": "What is done is done. What is next is next.", "author": "Unknown"},
    {"text": "The next right action is enough.", "author": "Unknown"},
]


def get_daily_quote(date_obj=None):
    if date_obj is None:
        date_obj = datetime.date.today()

    index = date_obj.toordinal() % len(QUOTES)
    return QUOTES[index].copy()
